"""Metric geometry for the playground: board calibration, tag poses, camera registration, triangulation.

Units: metres for every length (board squares, tag sizes, translations); pixels for image coordinates, with OpenCV's
convention that integer coordinates are pixel CENTRES ((0, 0) = centre of the top-left pixel).

Frames (verified by rendering at known poses on OpenCV 4.8-5.0 and pupil-apriltags 1.0; tests/test_playground_geometry.py):
- T_a_b maps b-frame coordinates to a-frame coordinates: p_a = T_a_b @ p_b (4x4, rotation + translation in metres).
- Camera: OpenCV axes, X right, Y down, Z forward along the optical axis. A camera pose is stored as T_world_cam
  (camera -> world; its translation is the camera centre); OpenCV's (rvec, tvec) is T_cam_world (X_cam = R X_world + t).
- World = the ChArUco board frame: origin at the TOP-LEFT outer corner of the printed board (as generated by
  CharucoBoard.generateImage and seen from the front), X along the squares_x edge (right), Y along the squares_y edge
  (down the page), Z = X x Y pointing INTO the board. Cameras that see the board are at Z < 0; for a board lying face-up
  on a table +Z points down into the table, so "above the table" is Z < 0. The first inner corner is (square_m, square_m, 0).
- AprilTag frame (pupil-apriltags = AprilTag 3): origin at the tag centre, X right, Y down, Z INTO the tag face, for the
  tag seen upright as in the official bitmaps (AprilRobotics apriltag-imgs; cv2.aruco's DICT_APRILTAG_36h11 images are those
  bitmaps rotated 180 deg). Same convention as the board: a tag printed upright on the board plane has R_world_tag = I.
  tag_size_m = edge of the BLACK border square (8 of the 10 cells of the official image, white quiet zone excluded).
- Head tag: T_tag_headcam = the head camera's pose in the tag frame (head-camera coords -> tag coords), so
  T_world_headcam = T_world_fixedcam @ T_fixedcam_tag @ T_tag_headcam (head_pose_from_tag).

Intrinsics carry the image size they belong to; functions taking an image assert it has that size (Intrinsics.scaled_to
converts e.g. a native 1920x1080 calibration to 640x360 extracted frames). Lens models: "pinhole" (OpenCV k1 k2 p1 p2
[k3]), "rational" (OpenCV 8/12/14 coefficients, CALIB_RATIONAL_MODEL) and "fisheye" (cv2.fisheye Kannala-Brandt k1..k4;
equidistant when all are zero). Wide lenses (GoPro-class) need "rational" or "fisheye". Detections are made on RAW
(distorted) images; points are undistorted with a converged solve (undistort_points) and returned in raw pixels.
Invalid inputs raise GeometryError; degenerate measurements return None (or NaN) instead of a confident wrong answer.
"""
from __future__ import annotations

import re
import threading
from dataclasses import dataclass
from functools import lru_cache
from itertools import combinations

import cv2
import numpy as np

from duet.geometry.transforms import rigid_matrix_errors

ARUCO_DICT = cv2.aruco.DICT_5X5_100
LENS_MODELS = ("pinhole", "rational", "fisheye")
_CRITERIA = (cv2.TERM_CRITERIA_COUNT | cv2.TERM_CRITERIA_EPS, 100, 1e-12)  # iterative undistortion: converge, don't stop at 5
_MIN_DEPTH_M = 0.01


class GeometryError(ValueError, AssertionError):
    """Invalid geometric input (image size vs intrinsics, non-rigid transform, implausible metric size, bad shapes).
    Subclasses both ValueError and AssertionError so callers written against either wording of the contract catch it."""


def _in_range(x, name: str, lo: float, hi: float, hint: str = "") -> float:
    v = float(x)
    if not (np.isfinite(v) and lo <= v <= hi):
        raise GeometryError(f"{name}={x!r} outside [{lo}, {hi}]{hint}")
    return v


def _as_gray(img, what: str = "image") -> np.ndarray:
    a = np.asarray(img) if img is not None else np.zeros(0)
    if a.ndim == 3 and a.shape[2] in (3, 4):
        a = cv2.cvtColor(a, cv2.COLOR_BGR2GRAY if a.shape[2] == 3 else cv2.COLOR_BGRA2GRAY)
    if a.ndim != 2 or a.size == 0 or a.dtype != np.uint8:
        raise GeometryError(f"{what}: expected a non-empty uint8 grayscale image, got shape {a.shape} dtype {a.dtype}")
    return np.ascontiguousarray(a)


def _cv_version() -> tuple[int, int]:
    m = re.match(r"(\d+)\.(\d+)", cv2.__version__)
    return (int(m.group(1)), int(m.group(2))) if m else (0, 0)


def _require_charuco_opencv() -> None:
    if _cv_version() < (4, 8):
        raise RuntimeError(f"ChArUco needs OpenCV >= 4.8 (found {cv2.__version__}): 4.7's CharucoBoard API treats ChArUco corners as "
                           "marker corners and returns wrong object points (130 px errors accepted); upgrade opencv-python")


# ----------------------------------------------------------------------------- board

@dataclass(frozen=True)
class BoardSpec:
    """ChArUco board. square_m / marker_m: printed edge lengths in METRES (range-checked, so 50 meaning mm fails loudly).
    legacy=True for boards generated by OpenCV < 4.6 or 'legacy' online generators (layouts differ when squares_y is even).
    dictionary: name of a cv2.aruco predefined dictionary."""
    squares_x: int = 7
    squares_y: int = 5
    square_m: float = 0.05
    marker_m: float = 0.037
    legacy: bool = False
    dictionary: str = "DICT_5X5_100"

    def __post_init__(self):
        for n in ("squares_x", "squares_y"):
            v = getattr(self, n)
            if isinstance(v, bool) or not float(v).is_integer() or not 3 <= int(v) <= 100:
                raise GeometryError(f"BoardSpec.{n}={v!r}: expected an integer 3-100")
        _in_range(self.square_m, "BoardSpec.square_m", 0.005, 1.0, " (metres)")
        _in_range(self.marker_m, "BoardSpec.marker_m", 0.002, 1.0, " (metres)")
        if not float(self.marker_m) < float(self.square_m):
            raise GeometryError(f"BoardSpec.marker_m={self.marker_m} must be smaller than square_m={self.square_m}")
        if not isinstance(self.dictionary, str) or not isinstance(getattr(cv2.aruco, self.dictionary, None), int):
            raise GeometryError(f"BoardSpec.dictionary={self.dictionary!r} is not a cv2.aruco predefined dictionary")

    def board(self) -> cv2.aruco.CharucoBoard:
        _require_charuco_opencv()
        b = cv2.aruco.CharucoBoard((int(self.squares_x), int(self.squares_y)), float(self.square_m), float(self.marker_m),
                                   cv2.aruco.getPredefinedDictionary(getattr(cv2.aruco, self.dictionary)))
        if self.legacy:
            b.setLegacyPattern(True)
        return b

    def corners_m(self) -> np.ndarray:
        """[n_inner, 3] board-frame positions of the ChArUco corners, indexed by ChArUco corner id."""
        return _board_corners(self).copy()


@lru_cache(maxsize=32)
def _board_corners(spec: BoardSpec) -> np.ndarray:
    return np.asarray(spec.board().getChessboardCorners(), float).reshape(-1, 3)


_LOCAL = threading.local()  # OpenCV detectors are cached per thread (not documented as thread-safe)


def _charuco_detector(spec: BoardSpec):
    cache = getattr(_LOCAL, "charuco", None)
    if cache is None:
        cache = _LOCAL.charuco = {}
    if spec not in cache:
        cache[spec] = cv2.aruco.CharucoDetector(spec.board())
    return cache[spec]


def detect_board(gray: np.ndarray, spec: BoardSpec, min_corners: int = 6):
    """ChArUco corners in a RAW image: (charuco_corners [N,1,2] float32 px, charuco_ids [N,1] int32) or (None, None)."""
    _require_charuco_opencv()
    corners, ids, _, _ = _charuco_detector(spec).detectBoard(_as_gray(gray, "detect_board image"))
    if corners is None or ids is None or len(ids) < min_corners or not np.isfinite(corners).all():
        return None, None
    if len(corners) != len(ids):
        raise RuntimeError(f"ChArUco detector returned {len(corners)} corners for {len(ids)} ids (OpenCV {cv2.__version__})")
    return corners, ids


def _num(x) -> float | None:
    """JSON-safe float (None for NaN / inf)."""
    return float(x) if x is not None and np.isfinite(x) else None


def _minor_extent(xy: np.ndarray) -> float:
    """RMS distance of 2-D points from their best-fit line (0 for collinear points)."""
    if len(xy) < 3:
        return 0.0
    return float(np.linalg.svd(xy - xy.mean(0), compute_uv=False)[1] / np.sqrt(len(xy)))


# ----------------------------------------------------------------------------- intrinsics

@dataclass
class Intrinsics:
    """Intrinsics for images of exactly width x height pixels. K: 3x3 (px). dist: per `model` (module docstring).
    source: provenance, e.g. "board", "rig_json", "zed_factory", "nominal_fov" (a guess, not a calibration)."""
    K: np.ndarray
    dist: np.ndarray
    width: int
    height: int
    model: str = "pinhole"
    source: str = ""
    rms_px: float | None = None

    def __post_init__(self):
        if not isinstance(self.model, str) or self.model not in LENS_MODELS:
            raise GeometryError(f"Intrinsics.model={self.model!r}: expected one of {LENS_MODELS}")
        K = np.array(self.K, dtype=float)
        d = np.array([] if self.dist is None else self.dist, dtype=float).ravel()
        if K.shape != (3, 3) or not np.isfinite(K).all() or K[0, 0] <= 0 or K[1, 1] <= 0 or abs(K[1, 0]) > 1e-9 * K[1, 1] or not np.allclose(K[2], [0, 0, 1]):
            raise GeometryError(f"Intrinsics.K must be a finite 3x3 camera matrix with fx, fy > 0 and last row [0, 0, 1]; got {K.tolist()}")
        if d.size == 0:
            d = np.zeros(4 if self.model == "fisheye" else 5)
        if not np.isfinite(d).all() or (d.size != 4 if self.model == "fisheye" else d.size not in (4, 5, 8, 12, 14)):
            raise GeometryError(f"Intrinsics.dist has {d.size} coefficients {d.tolist()}: model {self.model!r} takes "
                                f"{'4 (k1..k4)' if self.model == 'fisheye' else '4, 5, 8, 12 or 14 (OpenCV order)'}")
        w, h = self.width, self.height
        if isinstance(w, bool) or isinstance(h, bool) or not float(w).is_integer() or not float(h).is_integer() or int(w) <= 0 or int(h) <= 0:
            raise GeometryError(f"Intrinsics.width/height must be positive integers, got {w!r} x {h!r}")
        self.K, self.dist, self.width, self.height = K, d, int(w), int(h)
        self.rms_px = None if self.rms_px is None else float(self.rms_px)

    def to_json(self) -> dict:
        return {"K": self.K.tolist(), "dist": self.dist.ravel().tolist(), "width": self.width, "height": self.height, "model": self.model,
                "source": self.source, "rms_px": self.rms_px}

    @classmethod
    def from_json(cls, d: dict) -> Intrinsics:
        """Also reads files written before model/source existed: then the model follows OpenCV's own reading of the
        coefficient vector (<= 5 -> "pinhole", 8/12/14 -> "rational"); a fisheye lens must be declared explicitly. "dist"
        is required ([] = none): a missing key is not taken to mean an ideal lens."""
        if "dist" not in d or "K" not in d:
            raise GeometryError(f"intrinsics JSON needs 'K' and 'dist' (use [] for no distortion); got keys {sorted(d)}")
        dist = np.array(d["dist"] if d["dist"] is not None else [], float).ravel()
        model = d.get("model") or ("pinhole" if dist.size <= 5 else "rational")
        return cls(np.array(d["K"], float), dist, int(d["width"]), int(d["height"]), model, str(d.get("source") or ""), d.get("rms_px"))

    @classmethod
    def nominal(cls, width: int, height: int, fov_deg: float, axis: str = "horizontal", model: str = "pinhole") -> Intrinsics:
        """A GUESS from a quoted field of view (source="nominal_fov"): no distortion, principal point at the image centre.
        axis: image extent the FOV spans ("horizontal" = width, "vertical" = height, "diagonal"). model: "pinhole"
        (rectilinear lens, FOV < 180) or "fisheye" (equidistant r = f * theta). GoPro-class FOVs describe fisheye-like
        lenses: a pinhole with the same 120 deg HFOV over 1280 px has f = 369 px where the lens centre has ~611 px."""
        half = {"horizontal": width / 2, "vertical": height / 2, "diagonal": float(np.hypot(width, height)) / 2}.get(axis)
        if half is None:
            raise GeometryError(f"nominal: axis={axis!r} must be 'horizontal', 'vertical' or 'diagonal'")
        th = np.radians(_in_range(fov_deg, "fov_deg", 1.0, 179.0 if model == "pinhole" else 240.0)) / 2
        if model == "pinhole":
            f = half / np.tan(th)
        elif model == "fisheye":
            f = half / th
        else:
            raise GeometryError(f"nominal: model={model!r} must be 'pinhole' or 'fisheye'")
        K = np.array([[f, 0, (width - 1) / 2], [0, f, (height - 1) / 2], [0, 0, 1]], float)
        return cls(K, np.zeros(4 if model == "fisheye" else 5), width, height, model, "nominal_fov")

    def scaled_to(self, width: int, height: int) -> Intrinsics:
        """The same camera for images RESIZED from (self.width, self.height) to (width, height), e.g. a rig.json K at the
        native 1920x1080 -> 640x360 extracted frames. Pixel-centre convention u' = (u + 0.5) * s - 0.5; distortion acts on
        normalised coordinates and is unchanged. Raises GeometryError when the aspect ratio differs by > 1 % (a crop or a
        different sensor mode, which K alone cannot describe)."""
        sx, sy = width / self.width, height / self.height
        if not (sx > 0 and sy > 0) or abs(sx / sy - 1) > 0.01:
            raise GeometryError(f"scaled_to: {self.width}x{self.height} -> {width}x{height} changes the aspect ratio by "
                                f"{100 * abs(sx / sy - 1):.1f} % (> 1 %): not a resize of the calibrated image")
        K = self.K.copy()
        K[0, :2] *= sx; K[1, 1] *= sy; K[0, 2] = (K[0, 2] + 0.5) * sx - 0.5; K[1, 2] = (K[1, 2] + 0.5) * sy - 0.5
        rms = None if self.rms_px is None else self.rms_px * (sx + sy) / 2
        return Intrinsics(K, self.dist.copy(), int(width), int(height), self.model, self.source, rms)

    def check_image(self, img, what: str = "image") -> None:
        """Raise GeometryError unless img is height x width (the frame-size contract)."""
        h, w = np.asarray(img).shape[:2]
        if (h, w) != (self.height, self.width):
            raise GeometryError(f"{what} is {w}x{h} but the intrinsics ({self.source or 'unknown source'}) are for {self.width}x{self.height}; "
                                "rescale them with Intrinsics.scaled_to()")


@lru_cache(maxsize=256)
def _max_radius(model: str, dist: tuple) -> float:
    """Largest normalised radius |(X/Z, Y/Z)| up to which the model's radial mapping is monotonic. Beyond it a
    polynomial model folds back (rays far outside the calibrated field land inside the image). Tangential terms ignored."""
    if model == "fisheye":
        th = np.linspace(0, np.pi / 2 - 1e-3, 8001)[1:]
        k = np.asarray(dist, float); t2 = th * th
        thd = th * (1 + t2 * (k[0] + t2 * (k[1] + t2 * (k[2] + t2 * k[3]))))
        bad = np.nonzero(np.diff(thd) <= 0)[0]
        return float(np.tan(th[bad[0]])) if len(bad) else np.inf
    d = np.zeros(8); d[:min(8, len(dist))] = np.asarray(dist, float)[:8]
    k1, k2, _, _, k3, k4, k5, k6 = d
    r = np.linspace(0, 20.0, 40001)[1:]; r2 = r * r
    den = 1 + r2 * (k4 + r2 * (k5 + r2 * k6))
    rd = r * (1 + r2 * (k1 + r2 * (k2 + r2 * k3))) / np.where(den > 0, den, np.nan)
    bad = np.nonzero(~(np.diff(rd) > 0))[0]
    return float(r[bad[0]]) if len(bad) else np.inf


def _project_normalized(intr: Intrinsics, xy: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Normalised points (x, y) [M,2] -> raw pixels [M,2] and d(u, v)/d(x, y) [M,2,2] (OpenCV's own model + Jacobian)."""
    P = np.c_[xy, np.ones(len(xy))].reshape(-1, 1, 3); z = np.zeros(3)
    if intr.model == "fisheye":
        uv, jac = cv2.fisheye.projectPoints(P, z, z, intr.K, intr.dist.reshape(4, 1)); cols = slice(11, 13)
    else:
        uv, jac = cv2.projectPoints(P, z, z, intr.K, intr.dist); cols = slice(3, 5)
    return uv.reshape(-1, 2), np.asarray(jac)[:, cols].reshape(-1, 2, 2)


def undistort_points(intr: Intrinsics, px: np.ndarray) -> np.ndarray:
    """RAW (distorted) pixels [..., 2] -> undistorted NORMALISED image coordinates [..., 2] = (X/Z, Y/Z) in the camera
    frame (multiply by K for undistorted pixels; (x, y, 1) * Z is the camera-frame point at depth Z). OpenCV's iterative
    solve with explicit criteria, polished by Newton steps on the forward model and verified (re-projects within 1e-3 px).
    NaN where the input is not finite or the lens model cannot be inverted (beyond its monotonic range)."""
    p = np.asarray(px, dtype=float)
    if p.ndim == 0 or p.shape[-1] != 2:
        raise GeometryError(f"undistort_points: expected [..., 2] pixels, got shape {p.shape}")
    flat = p.reshape(-1, 2); out = np.full(flat.shape, np.nan); ok = np.isfinite(flat).all(1)
    if ok.any():
        src = flat[ok]; s = src.reshape(-1, 1, 2)
        if intr.model == "fisheye":
            n = cv2.fisheye.undistortPoints(s, intr.K, intr.dist.reshape(4, 1), criteria=_CRITERIA)
        elif hasattr(cv2, "undistortPointsIter"):  # OpenCV 4.x: plain undistortPoints stops after 5 iterations
            n = cv2.undistortPointsIter(s, intr.K, intr.dist, None, None, _CRITERIA)
        else:  # OpenCV 5: undistortPoints takes the criteria
            n = cv2.undistortPoints(s, intr.K, intr.dist, criteria=_CRITERIA)
        n = np.asarray(n, float).reshape(-1, 2)
        lin = (src - intr.K[:2, 2]) / np.diag(intr.K)[:2]
        n = np.where(np.isfinite(n), n, lin)
        for _ in range(4):
            uv, J = _project_normalized(intr, n); r = src - uv
            det = J[:, 0, 0] * J[:, 1, 1] - J[:, 0, 1] * J[:, 1, 0]
            safe = np.abs(det) > 1e-12
            step = np.zeros_like(n)
            step[safe, 0] = (J[safe, 1, 1] * r[safe, 0] - J[safe, 0, 1] * r[safe, 1]) / det[safe]
            step[safe, 1] = (-J[safe, 1, 0] * r[safe, 0] + J[safe, 0, 0] * r[safe, 1]) / det[safe]
            n = n + step
        uv, _ = _project_normalized(intr, n)
        good = np.isfinite(n).all(1) & (np.linalg.norm(uv - src, axis=1) < 1e-3) & (np.hypot(n[:, 0], n[:, 1]) < _max_radius(intr.model, tuple(intr.dist)))
        res = np.full_like(n, np.nan); res[good] = n[good]; out[ok] = res
    return out.reshape(p.shape)


def project_cam(intr: Intrinsics, pts_cam: np.ndarray) -> np.ndarray:
    """Camera-frame points [..., 3] (metres) -> RAW pixels [M, 2]. NaN for points at depth <= 0, non-finite points and
    rays beyond the lens model's monotonic range (where a polynomial model would fold them back into the image)."""
    Xc = np.asarray(pts_cam, float).reshape(-1, 3); out = np.full((len(Xc), 2), np.nan)
    ok = np.isfinite(Xc).all(1) & (Xc[:, 2] > 1e-9)
    if ok.any():
        idx = np.nonzero(ok)[0]
        idx = idx[np.hypot(Xc[idx, 0], Xc[idx, 1]) / Xc[idx, 2] < _max_radius(intr.model, tuple(intr.dist))]
        if len(idx):
            out[idx] = _project_normalized(intr, Xc[idx, :2] / Xc[idx, 2:3])[0]
    return out


def project(intr: Intrinsics, T_cam_world: np.ndarray, pts_world: np.ndarray) -> np.ndarray:
    """World points [..., 3] -> RAW pixels [M, 2] for a camera with pose T_cam_world (world -> camera). NaN where the
    point is behind the camera or outside the lens model's range (see project_cam)."""
    T = validate_rigid(T_cam_world, "T_cam_world")
    X = np.asarray(pts_world, float).reshape(-1, 3)
    return project_cam(intr, X @ T[:3, :3].T + T[:3, 3])


# ----------------------------------------------------------------------------- planar poses (board, tags)

def _planar_pose_candidates(obj: np.ndarray, px: np.ndarray, intr: Intrinsics, flags: int, refine: bool) -> list[tuple[np.ndarray, float]]:
    """PnP for planar object points (z = 0) on undistorted normalised coordinates -> [(T_cam_obj, mean raw-px error)],
    best first; only solutions with every point in front of the camera and finite errors."""
    n = undistort_points(intr, px); ok = np.isfinite(n).all(1)
    if ok.sum() < 4:
        return []
    o, nn, pp = obj[ok].astype(np.float64), n[ok].astype(np.float64), px[ok].astype(np.float64)
    try:
        _, rvecs, tvecs, _ = cv2.solvePnPGeneric(o, nn, np.eye(3), None, flags=flags)
    except cv2.error:
        return []
    out = []
    for rv, tv in zip(rvecs, tvecs):
        if refine:
            try:  # ML refinement: pixel space through the full model; fisheye in normalised space (no fisheye LM in OpenCV)
                rv, tv = (cv2.solvePnPRefineLM(o, pp, intr.K, intr.dist, rv.copy(), tv.copy()) if intr.model != "fisheye"
                          else cv2.solvePnPRefineLM(o, nn, np.eye(3), None, rv.copy(), tv.copy()))
            except cv2.error:
                pass
        if not (np.isfinite(rv).all() and np.isfinite(tv).all()):
            continue
        T = rt_to_T(rv, tv); Xc = o @ T[:3, :3].T + T[:3, 3]
        if (Xc[:, 2] <= _MIN_DEPTH_M).any():
            continue
        e = np.linalg.norm(project_cam(intr, Xc) - pp, axis=1)
        if np.isfinite(e).all():
            out.append((T, float(e.mean())))
    return sorted(out, key=lambda s: s[1])


def pose_from_board_corners(corners: np.ndarray, ids: np.ndarray, intr: Intrinsics, spec: BoardSpec, max_err_px: float = 10.0) -> tuple[np.ndarray, float] | None:
    """T_cam_board and mean reprojection error (raw px) from detected ChArUco corners (RAW pixels) and ids. None when
    degenerate: < 6 corners, (nearly) collinear corners (rotation about the line is free), non-finite values, a solution
    behind the camera, or mean error > max_err_px."""
    img = np.asarray(corners, float).reshape(-1, 2); ids = np.asarray(ids).ravel().astype(int)
    if len(img) != len(ids):
        raise GeometryError(f"{len(img)} corners but {len(ids)} ids")
    cc = _board_corners(spec)
    if len(ids) and (ids.min() < 0 or ids.max() >= len(cc)):
        raise GeometryError(f"ChArUco ids {ids.min()}..{ids.max()} do not belong to a {spec.squares_x}x{spec.squares_y} board")
    if len(ids) < 6 or not np.isfinite(img).all():
        return None
    obj = cc[ids]
    if _minor_extent(obj[:, :2]) < 0.25 * spec.square_m:
        return None
    cands = _planar_pose_candidates(obj, img, intr, cv2.SOLVEPNP_IPPE, refine=True)
    if not cands or cands[0][1] > max_err_px:
        return None
    return cands[0]


def board_pose(gray: np.ndarray, intr: Intrinsics, spec: BoardSpec, max_err_px: float = 10.0) -> tuple[np.ndarray, float] | None:
    """T_cam_board (board -> camera, metres) from one RAW image, plus the mean reprojection error in raw pixels; None if
    the board is not seen or the view is degenerate (pose_from_board_corners). Raises GeometryError when the image is not
    intr.width x intr.height."""
    g = _as_gray(gray, "board_pose image"); intr.check_image(g, "board_pose image")
    c, i = detect_board(g, spec)
    return None if c is None else pose_from_board_corners(c, i, intr, spec, max_err_px)


def _fisheye_flag(name: str) -> int:
    """cv2.fisheye.CALIB_* on OpenCV 4.x; unified into cv2.CALIB_* (with other values) on 5.x."""
    v = getattr(cv2.fisheye, name, None)
    return int(v if v is not None else getattr(cv2, name))


# per model: flag sets tried in order; the later ones drop the highest radial terms when a fit folds or has a pole
_FIT_ATTEMPTS = {"pinhole": ((), ("CALIB_FIX_K3",)), "rational": (("CALIB_RATIONAL_MODEL",), ("CALIB_RATIONAL_MODEL", "CALIB_FIX_K5", "CALIB_FIX_K6")),
                 "fisheye": ((), ("CALIB_FIX_K3", "CALIB_FIX_K4"))}


def _calibrate_once(model: str, obj: list, img: list, size: tuple[int, int], extra: tuple = ()):
    """-> (K, dist, rvecs, tvecs, std [fx, fy, cx, cy] or None) or None if OpenCV fails."""
    crit = (cv2.TERM_CRITERIA_COUNT | cv2.TERM_CRITERIA_EPS, 200, 1e-12)
    try:
        if model == "fisheye":
            flags = 0
            for n in ("CALIB_RECOMPUTE_EXTRINSIC", "CALIB_FIX_SKEW", *extra):
                flags |= _fisheye_flag(n)
            o = [x.reshape(1, -1, 3).astype(np.float64) for x in obj]; i = [x.reshape(1, -1, 2).astype(np.float64) for x in img]  # (1,N,C) or it fails
            _, K, D, rv, tv = cv2.fisheye.calibrate(o, i, size, np.eye(3), np.zeros((4, 1)), flags=flags, criteria=crit)
            return K, np.asarray(D, float).ravel(), rv, tv, None
        flags = 0
        for n in extra:
            flags |= int(getattr(cv2, n))
        o = [x.astype(np.float32) for x in obj]; i = [x.reshape(-1, 1, 2).astype(np.float32) for x in img]
        _, K, D, rv, tv, std, _, _ = cv2.calibrateCameraExtended(o, i, size, None, None, flags=flags, criteria=crit)
        D = np.asarray(D, float).ravel()
        return K, (D[:8] if D.size > 8 and not D[8:].any() else D), rv, tv, np.asarray(std, float).ravel()[:4]  # rational: 14 -> 8 when unused
    except cv2.error:
        return None


def _cam_points(obj: np.ndarray, rvec, tvec) -> np.ndarray:
    return obj @ rt_to_T(rvec, tvec)[:3, :3].T + np.asarray(tvec, float).ravel()


def _fit_model(model: str, obj: list, img: list, size: tuple[int, int]):
    """Fit `model`, retrying with fewer radial terms while the fitted radial mapping folds back or has a pole inside the
    field covered by the data (an over-parameterised fit, e.g. a near pole-zero cancellation of the rational model).
    -> (Intrinsics, rvecs, tvecs, std or None, flags used) or None."""
    for extra in _FIT_ATTEMPTS[model]:
        fit = _calibrate_once(model, obj, img, size, extra)
        if fit is None:
            continue
        K, dist, rv, tv, std = fit
        try:
            intr = Intrinsics(K, dist, size[0], size[1], model, "board")
        except GeometryError:
            continue
        Xc = [_cam_points(o, r, t) for o, r, t in zip(obj, rv, tv)]
        if min(float(x[:, 2].min()) for x in Xc) <= 0:
            continue
        r_data = max(float((np.hypot(x[:, 0], x[:, 1]) / x[:, 2]).max()) for x in Xc)
        if 1.05 * r_data < _max_radius(model, tuple(intr.dist)):
            return intr, rv, tv, std, list(extra)
    return None


def _rms(intr: Intrinsics, obj: list, img: list, rvecs, tvecs) -> tuple[float, list[float]]:
    """Overall and per-view RMS reprojection error (raw px); inf where a point cannot be projected."""
    errs = [project_cam(intr, _cam_points(o, r, t)) - im for o, im, r, t in zip(obj, img, rvecs, tvecs)]
    per = [float(np.sqrt(np.mean(np.sum(e ** 2, axis=1)))) if np.isfinite(e).all() else np.inf for e in errs]
    e = np.concatenate(errs)
    return (float(np.sqrt(np.mean(np.sum(e ** 2, axis=1)))) if np.isfinite(e).all() else np.inf), per


def _std_from_jacobian(intr: Intrinsics, obj: list, img: list, rvecs, tvecs) -> np.ndarray:
    """1-sigma of (fx, fy, cx, cy) from the Gauss-Newton normal matrix of all reprojection residuals (used for fisheye,
    where OpenCV reports none). inf when the problem is singular."""
    n_int = 8 if intr.model == "fisheye" else 4 + intr.dist.size
    M = sum(len(o) for o in obj); P = n_int + 6 * len(obj)
    J = np.zeros((2 * M, P)); res = []; row = 0
    for v, (o, im) in enumerate(zip(obj, img)):
        o3 = o.reshape(-1, 1, 3).astype(np.float64); k = len(o)
        if intr.model == "fisheye":
            uv, jac = cv2.fisheye.projectPoints(o3, rvecs[v], tvecs[v], intr.K, intr.dist.reshape(4, 1))
            J[row:row + 2 * k, :8] = jac[:, :8]; J[row:row + 2 * k, n_int + 6 * v:n_int + 6 * v + 6] = jac[:, 8:14]
        else:
            uv, jac = cv2.projectPoints(o3, rvecs[v], tvecs[v], intr.K, intr.dist)
            J[row:row + 2 * k, :4] = jac[:, 6:10]; J[row:row + 2 * k, 4:n_int] = jac[:, 10:10 + intr.dist.size]
            J[row:row + 2 * k, n_int + 6 * v:n_int + 6 * v + 6] = jac[:, :6]
        res.append(uv.reshape(-1, 2) - im.reshape(-1, 2)); row += 2 * k
    r = np.concatenate(res).ravel(); dof = max(1, len(r) - P)
    try:
        with np.errstate(all="ignore"):  # some macOS BLAS builds raise spurious FP flags in matmul; finiteness is checked below
            d = np.diag(np.linalg.inv(J.T @ J))[:4] * (r @ r) / dof
    except np.linalg.LinAlgError:
        return np.full(4, np.inf)
    return np.where(np.isfinite(d) & (d >= 0), np.sqrt(np.abs(d)), np.inf)


def calibrate_intrinsics_report(frames: list[np.ndarray], spec: BoardSpec, model: str = "pinhole", **kw) -> tuple[Intrinsics | None, dict]:
    """Intrinsics from RAW grayscale views of a board seen from DIFFERENT ORIENTATIONS (moving board or moving camera),
    plus a JSON-able report (see calibrate_from_corners_report for the acceptance checks and the reason)."""
    frames = list(frames)
    if not frames:
        return None, {"model": model, "n_frames": 0, "ok": False, "reason": "no frames"}
    shapes = {np.asarray(f).shape[:2] for f in frames}
    if len(shapes) != 1:
        raise GeometryError(f"calibration frames differ in size: {sorted(shapes)}")
    h, w = shapes.pop(); det = [detect_board(g, spec, min_corners=kw.get("min_corners", 8)) for g in frames]
    intr, rep = calibrate_from_corners_report([c for c, _ in det], [i for _, i in det], (w, h), spec, model, **kw)
    rep["n_frames"] = len(frames)
    return intr, rep


def calibrate_from_corners_report(corners: list, ids: list, image_size: tuple[int, int], spec: BoardSpec, model: str = "pinhole", *,
                                  min_views: int = 8, min_corners: int = 8, min_tilt_deg: float = 15.0, max_rms_px: float = 1.0,
                                  max_rel_std_f: float = 0.01, max_std_c_frac: float = 0.01) -> tuple[Intrinsics | None, dict]:
    """Calibration from per-view ChArUco detections (corners [N,1,2] or [N,2] RAW px, ids [N]; None entries = no board).
    image_size = (width, height). Returns (None, report) with report["reason"] instead of a confident wrong answer when:
    fewer than min_views views with >= min_corners non-collinear corners; no 3 views whose board normals differ pairwise
    by >= min_tilt_deg (a fixed camera watching the board slide on one table plane cannot determine f or the principal
    point); final RMS > max_rms_px; 1-sigma of fx/fy > max_rel_std_f * f or of cx/cy > max_std_c_frac * image size;
    principal point outside the central 60 %; a pinhole fit > 10 % worse than a rational fit of the same views (wide lens);
    OpenCV failure. Views whose RMS exceeds max(3 x median, 0.5 px) are dropped (report["dropped_views"] = their indices)
    and the fit repeated; fits whose radial mapping folds inside the data are retried with fewer radial terms
    (report["flags"]). report["coverage"] (fraction of an 8x6 image grid holding corners) and ["max_radius_frac"] tell how
    much of the field the calibration actually constrains: outside it the model is extrapolated."""
    if model not in LENS_MODELS:
        raise GeometryError(f"calibrate_intrinsics: model={model!r} not in {LENS_MODELS}")
    if len(corners) != len(ids):
        raise GeometryError(f"{len(corners)} corner sets but {len(ids)} id sets")
    w, h = int(image_size[0]), int(image_size[1])
    rep: dict = {"model": model, "n_frames": len(corners), "n_views": 0, "n_used": 0, "dropped_views": [], "rms_px": None, "per_view_rms_px": [],
                 "std_px": None, "max_tilt_deg": None, "tilt_ok": False, "ok": False, "reason": ""}
    cc = _board_corners(spec); views = []
    for k, (c, i) in enumerate(zip(corners, ids)):
        if c is None or i is None:
            continue
        c = np.asarray(c, float).reshape(-1, 2); i = np.asarray(i).ravel().astype(int)
        if len(c) != len(i) or (len(i) and (i.min() < 0 or i.max() >= len(cc))):
            raise GeometryError(f"view {k}: {len(c)} corners / {len(i)} ids not from a {spec.squares_x}x{spec.squares_y} board")
        if len(i) >= min_corners and np.isfinite(c).all() and _minor_extent(cc[i, :2]) >= 0.5 * spec.square_m:
            views.append((k, cc[i], c))
    rep["n_views"] = len(views)
    if len(views) < min_views:
        rep["reason"] = f"board seen well in {len(views)} of {len(corners)} frames (need >= {min_views})"; return None, rep
    keep = list(range(len(views)))
    while True:  # refit until no view is inconsistent (at most half of the views are ever dropped)
        obj, img = [views[j][1] for j in keep], [views[j][2] for j in keep]
        fit = _fit_model(model, obj, img, (w, h))
        if fit is None:
            rep["reason"] = f"OpenCV {model} calibration failed or folded inside the data's field of view"; return None, rep
        intr, rvecs, tvecs, std, flags = fit
        rms, per_view = _rms(intr, obj, img, rvecs, tvecs)
        thr = max(3 * float(np.median(per_view)), 0.5)
        bad = [j for j, e in zip(keep, per_view) if not e <= thr]
        if not bad or len(keep) - len(bad) < min_views or len(views) - len(keep) + len(bad) > len(views) // 2:
            break
        rep["dropped_views"] += [views[j][0] for j in bad]; keep = [j for j in keep if j not in bad]
    if std is None:
        std = _std_from_jacobian(intr, obj, img, rvecs, tvecs)
    normals = np.array([cv2.Rodrigues(np.asarray(rv, float))[0][:, 2] for rv in rvecs])
    ang = np.degrees(np.arccos(np.clip(normals @ normals.T, -1, 1)))
    adj = (ang >= min_tilt_deg).astype(int)
    pts = np.concatenate(img); cells = {(int(u * 8 // w), int(v * 6 // h)) for u, v in pts if 0 <= u < w and 0 <= v < h}
    K = intr.K; fx, fy, cx, cy = K[0, 0], K[1, 1], K[0, 2], K[1, 2]
    rep.update(n_used=len(keep), rms_px=_num(rms), per_view_rms_px=[_num(round(e, 4)) for e in per_view], std_px=dict(zip(("fx", "fy", "cx", "cy"), map(_num, std))),
               max_tilt_deg=float(ang.max()), tilt_ok=bool(((adj @ adj) * adj).any()), K=K.tolist(), dist=intr.dist.tolist(), flags=flags,
               coverage=len(cells) / 48.0, max_radius_frac=float(np.hypot(*(pts - [cx, cy]).T).max() / np.hypot(max(cx, w - 1 - cx), max(cy, h - 1 - cy))))
    rich = _fit_model("rational", obj, img, (w, h)) if model == "pinhole" else None
    if rich is not None:  # a structurally inadequate model (e.g. pinhole on a GoPro-class lens) still fits the data to a few 0.1 px
        rep["rms_px_rational"] = _num(_rms(rich[0], obj, img, rich[1], rich[2])[0])
    if not rms <= max_rms_px:
        rep["reason"] = f"RMS {rms:.2f} px > {max_rms_px} px (wrong board spec, blur, or lens model {model!r} too simple)"
    elif rep.get("rms_px_rational") is not None and rms > 1.1 * rep["rms_px_rational"] + 0.02:
        rep["reason"] = (f"pinhole model too simple for this lens: RMS {rms:.3f} px vs {rep['rms_px_rational']:.3f} px with model='rational' "
                         "(biased focal length / principal point); recalibrate with model='rational' or 'fisheye'")
    elif not rep["tilt_ok"]:
        rep["reason"] = (f"insufficient tilt diversity: no 3 views with board normals >= {min_tilt_deg} deg apart (max {ang.max():.1f} deg); "
                         "tilt the board (or camera) in different directions")
    elif not (std[0] <= max_rel_std_f * fx and std[1] <= max_rel_std_f * fy and std[2] <= max_std_c_frac * w and std[3] <= max_std_c_frac * h):
        rep["reason"] = f"poorly constrained intrinsics: 1-sigma fx {std[0]:.1f} fy {std[1]:.1f} cx {std[2]:.1f} cy {std[3]:.1f} px"
    elif not (0.2 * w <= cx <= 0.8 * w and 0.2 * h <= cy <= 0.8 * h):
        rep["reason"] = f"principal point ({cx:.0f}, {cy:.0f}) implausibly far from the image centre"
    else:
        rep["ok"] = True; intr.rms_px = rms
        return intr, rep
    return None, rep


def calibrate_intrinsics(frames: list[np.ndarray], spec: BoardSpec, model: str = "pinhole", **kw) -> Intrinsics | None:
    """Intrinsics (source="board") from >= 8 RAW board views with diverse tilts; None when the views cannot determine
    them. See calibrate_intrinsics_report for the checks and the reason."""
    return calibrate_intrinsics_report(frames, spec, model, **kw)[0]


# ----------------------------------------------------------------------------- tags

@dataclass
class TagDetection:
    """One AprilTag. corners_px [4,2]: RAW (distorted) image pixels, OpenCV pixel-centre convention (pupil-apriltags'
    pixel-corner values minus 0.5), in AprilTag 3 order = tag-frame corners (-s,+s), (+s,+s), (+s,-s), (-s,-s),
    s = tag_size/2 (bottom-left, bottom-right, top-right, top-left of the upright tag).
    T_cam_tag: tag -> camera (tag frame: centre origin, X right, Y down, Z into the face; module docstring), None without
    intrinsics. err_px: mean reprojection error of the 4 corners in raw pixels. T_cam_tag_alt / alt_err_px: the second
    planar-ambiguity (IPPE) solution; when alt_err_px is close to err_px (small, distant or fronto-parallel tags) the
    tag's ORIENTATION is ambiguous (its position is not)."""
    tag_id: int
    corners_px: np.ndarray
    T_cam_tag: np.ndarray | None
    err_px: float | None
    T_cam_tag_alt: np.ndarray | None = None
    alt_err_px: float | None = None
    hamming: int = 0
    decision_margin: float = float("nan")
    family: str = ""


def tag_object_points(tag_size_m: float) -> np.ndarray:
    """[4,3] tag-frame corners (metres) in detection order (TagDetection); identical to OpenCV's SOLVEPNP_IPPE_SQUARE order."""
    s = _in_range(tag_size_m, "tag_size_m", 0.005, 2.0, " (metres, edge of the black border square)") / 2
    return np.array([[-s, s, 0], [s, s, 0], [s, -s, 0], [-s, -s, 0]], float)


_TAG_DETECTORS: dict = {}
_TAG_LOCK = threading.Lock()


def _tag_detector(families: str):
    """(detector, lock) per families string; a pupil-apriltags Detector must not run detect() from two threads at once."""
    with _TAG_LOCK:
        if families not in _TAG_DETECTORS:
            import pupil_apriltags as apr
            _TAG_DETECTORS[families] = (apr.Detector(families=families, nthreads=4, quad_decimate=1.0, refine_edges=True), threading.Lock())
        return _TAG_DETECTORS[families]


def detect_tags(gray: np.ndarray, intr: Intrinsics | None, tag_size_m: float, families: str = "tag36h11") -> list[TagDetection]:
    """AprilTags in a RAW image. Detection runs on the raw pixels (undistorting the whole image crops a wide lens' field);
    the 4 corners are undistorted with the full lens model and the pose solved with SOLVEPNP_IPPE_SQUARE (both planar
    solutions kept). tag_size_m: black-border edge in metres. With intr=None only ids/corners are returned. Raises
    GeometryError when the image is not intr.width x intr.height."""
    g = _as_gray(gray, "detect_tags image")
    obj = None
    if intr is not None:
        intr.check_image(g, "detect_tags image"); obj = tag_object_points(tag_size_m)
    det, lock = _tag_detector(families)
    with lock:
        raw = det.detect(g)
    out = []
    for d in raw:
        c = np.asarray(d.corners, float).reshape(4, 2) - 0.5; sols = []  # AprilTag: (0, 0) = top-left pixel's CORNER -> OpenCV centres
        if obj is not None:
            sols = _planar_pose_candidates(obj, c, intr, cv2.SOLVEPNP_IPPE_SQUARE, refine=False)
        fam = d.tag_family.decode() if isinstance(d.tag_family, bytes) else str(d.tag_family)
        (T, e), (T2, e2) = (sols + [(None, None), (None, None)])[:2]
        out.append(TagDetection(int(d.tag_id), c, T, e, T2, e2, int(d.hamming), float(d.decision_margin), fam))
    return out


# ----------------------------------------------------------------------------- transforms

def validate_rigid(T: np.ndarray, name: str = "T", atol: float = 1e-5) -> np.ndarray:
    """T as a float64 4x4 after checking it is a proper rigid transform: finite, bottom row (0, 0, 0, 1), rotation block
    orthonormal and det +1 (absolute tolerance atol; float32-stored poses pass). Never repairs; raises GeometryError."""
    errs = rigid_matrix_errors(T, tolerance=atol)
    if errs:
        raise GeometryError(f"{name} is not a rigid transform: {'; '.join(errs)}")
    return np.array(T, dtype=float)


def rt_to_T(rvec, tvec) -> np.ndarray:
    """OpenCV (rvec, tvec) -> 4x4 T (for solvePnP output this is T_cam_obj)."""
    R, _ = cv2.Rodrigues(np.asarray(rvec, float).reshape(3, 1)); T = np.eye(4); T[:3, :3] = R; T[:3, 3] = np.asarray(tvec, float).ravel(); return T


def inv(T: np.ndarray) -> np.ndarray:
    """Inverse of a rigid transform (validated): inv(T_a_b) = T_b_a."""
    T = validate_rigid(T); R, t = T[:3, :3], T[:3, 3]; Ti = np.eye(4); Ti[:3, :3] = R.T; Ti[:3, 3] = -R.T @ t; return Ti


def apply(T: np.ndarray, p: np.ndarray) -> np.ndarray:
    """T [4,4] applied to points [..., 3]."""
    return p @ T[:3, :3].T + T[:3, 3]


def head_pose_from_tag(T_world_fixedcam: np.ndarray, T_fixedcam_tag: np.ndarray, T_tag_headcam: np.ndarray) -> np.ndarray:
    """T_world_headcam from a fixed camera seeing the head tag. T_fixedcam_tag: TagDetection.T_cam_tag. T_tag_headcam: the
    head camera's pose IN THE TAG FRAME (head-camera coords -> tag coords), measured once per rig. Example: a tag worn
    upright on the forehead facing forward with the lens 5 cm below its centre: tag X = wearer's left, Y = down, Z = into
    the head (backwards), so R_tag_headcam = diag(-1, 1, -1), t = (0, 0.05, 0). Identity is NOT a neutral default: it
    means the camera looks through the back of the tag (into its face)."""
    return (validate_rigid(T_world_fixedcam, "T_world_fixedcam") @ validate_rigid(T_fixedcam_tag, "T_fixedcam_tag")
            @ validate_rigid(T_tag_headcam, "T_tag_headcam"))


def average_rotations(Rs: np.ndarray, weights: np.ndarray | None = None) -> np.ndarray:
    """Chordal L2 mean of rotations [N,3,3]: the rotation nearest (Frobenius) to sum_i w_i R_i."""
    Rs = np.asarray(Rs, float).reshape(-1, 3, 3)
    w = np.ones(len(Rs)) if weights is None else np.asarray(weights, float).ravel()
    if len(Rs) == 0 or len(w) != len(Rs) or not np.isfinite(Rs).all() or not (w >= 0).all() or w.sum() <= 0:
        raise GeometryError("average_rotations: need >= 1 finite rotation and matching non-negative weights")
    U, _, Vt = np.linalg.svd(np.einsum("n,nij->ij", w, Rs))
    return U @ np.diag([1, 1, np.sign(np.linalg.det(U @ Vt))]) @ Vt


def fit_similarity(src: np.ndarray, dst: np.ndarray, with_scale: bool = True, min_minor_ratio: float = 0.02) -> tuple[np.ndarray, float] | None:
    """Umeyama least squares dst ~= s * R @ src + t for matched points [N,3]. Returns (T [4,4] holding R and t, s), or None
    when the rotation is undetermined: < 3 points, or src (nearly) collinear, i.e. second singular value of the centred
    points < min_minor_ratio x the first (two distinct camera centres leave the rotation about their baseline free; use
    similarity_from_camera_poses)."""
    src = np.asarray(src, float); dst = np.asarray(dst, float)
    if src.shape != dst.shape or src.ndim != 2 or src.shape[1] != 3:
        raise GeometryError(f"fit_similarity: src {src.shape} and dst {dst.shape} must both be [N, 3]")
    if len(src) < 3 or not (np.isfinite(src).all() and np.isfinite(dst).all()):
        return None
    mu_s, mu_d = src.mean(0), dst.mean(0); S, D = src - mu_s, dst - mu_d
    sv = np.linalg.svd(S, compute_uv=False)
    if sv[0] <= 0 or sv[1] < min_minor_ratio * sv[0]:
        return None
    U, sig, Vt = np.linalg.svd(D.T @ S / len(src)); Dm = np.diag([1, 1, np.sign(np.linalg.det(U @ Vt))])
    R = U @ Dm @ Vt; s = float((sig * np.diag(Dm)).sum() / ((S ** 2).sum() / len(src))) if with_scale else 1.0
    T = np.eye(4); T[:3, :3] = R; T[:3, 3] = mu_d - s * R @ mu_s
    return T, s


def similarity_from_camera_poses(T_a_cams: np.ndarray, T_b_cams: np.ndarray, with_scale: bool = True) -> tuple[np.ndarray, float] | None:
    """(T_b_a as [4,4] R|t, s) with X_b = s R X_a + t, from the SAME cameras' poses in frames a and b ([N,4,4], camera ->
    frame; e.g. a = COLMAP model, b = board world). Rotation = chordal mean of R_b_cam R_a_cam^T, so it is determined even
    by one or two cameras (unlike fit_similarity on camera centres). Scale needs >= 2 distinct centres (None otherwise
    when with_scale). Poses in a must share one scale (a similarity frame), rotations must be proper."""
    A = np.asarray(T_a_cams, float).reshape(-1, 4, 4); B = np.asarray(T_b_cams, float).reshape(-1, 4, 4)
    if len(A) != len(B) or len(A) == 0:
        raise GeometryError(f"similarity_from_camera_poses: {len(A)} vs {len(B)} poses")
    for k in range(len(A)):
        validate_rigid(A[k], f"T_a_cams[{k}]"); validate_rigid(B[k], f"T_b_cams[{k}]")
    R = average_rotations(np.einsum("nij,nkj->nik", B[:, :3, :3], A[:, :3, :3]))
    ca, cb = A[:, :3, 3], B[:, :3, 3]; ca0, cb0 = ca - ca.mean(0), cb - cb.mean(0)
    s = 1.0
    if with_scale:
        den = float((ca0 ** 2).sum())
        if den <= 1e-12 * max(1.0, float((ca ** 2).sum())):
            return None
        s = float(np.einsum("ni,ni->", cb0, ca0 @ R.T) / den)
        if not s > 0:
            return None
    T = np.eye(4); T[:3, :3] = R; T[:3, 3] = cb.mean(0) - s * R @ ca.mean(0)
    return T, s


# ----------------------------------------------------------------------------- triangulation

@dataclass
class Camera:
    name: str
    intr: Intrinsics
    T_world_cam: np.ndarray  # 4x4 camera -> world (validated)

    def __post_init__(self):
        self.T_world_cam = validate_rigid(self.T_world_cam, f"Camera {self.name!r} T_world_cam")

    @property
    def P(self) -> np.ndarray:
        """3x4 K [R|t]: world points -> UNDISTORTED pixel coordinates. Raw detections must be undistorted first
        (K @ undistort_points(...)) before they can be used with P."""
        T_cw = inv(self.T_world_cam); return self.intr.K @ T_cw[:3, :4]


def _tri_solve(R: np.ndarray, t: np.ndarray, f: np.ndarray, xn: np.ndarray, w: np.ndarray, mask: np.ndarray, iters: int) -> np.ndarray:
    """Weighted DLT + Gauss-Newton on (focal-scaled) normalised reprojection error for N points at once.
    R [C,3,3], t [C,3]: world -> camera; f [C] px; xn [C,N,2] undistorted normalised obs; w [C,N] weights; mask [C,N]."""
    C, N = mask.shape
    s = np.where(mask, np.sqrt(np.clip(np.where(mask, w, 0.0), 0, None)) * f[:, None], 0.0)
    x = np.where(mask[..., None], xn, 0.0)
    P = np.concatenate([R, t[:, :, None]], axis=2)
    r1 = x[..., 0, None] * P[:, None, 2, :] - P[:, None, 0, :]
    r2 = x[..., 1, None] * P[:, None, 2, :] - P[:, None, 1, :]
    A = np.transpose(np.concatenate([r1 * s[..., None], r2 * s[..., None]], axis=0), (1, 0, 2))  # [N, 2C, 4]
    X = np.full((N, 3), np.nan); ok = mask.sum(0) >= 2
    if not ok.any():
        return X
    Xh = np.linalg.svd(A[ok])[2][:, -1, :]
    hw = Xh[:, 3]; fin = np.abs(hw) > 1e-9 * np.linalg.norm(Xh[:, :3], axis=1)  # |w| ~ 0: rays (nearly) parallel -> infinity
    Xo = np.full((ok.sum(), 3), np.nan); Xo[fin] = Xh[fin, :3] / hw[fin, None]; X[ok] = Xo
    live = np.isfinite(X).all(1)
    with np.errstate(over="ignore", invalid="ignore"):  # points diverging to infinity are rejected by the caller's range check
        for _ in range(iters):
            if not live.any():
                break
            Xc = np.einsum("cij,nj->cni", R, np.where(live[:, None], X, 0.0)) + t[:, None, :]
            z = Xc[..., 2]; g = mask & (z > 1e-9); zi = np.where(g, 1.0 / np.where(g, z, 1.0), 0.0)
            u, v = Xc[..., 0] * zi, Xc[..., 1] * zi; sg = s * g
            res = np.stack([u - x[..., 0], v - x[..., 1]], -1) * sg[..., None]
            Jc = np.zeros((C, N, 2, 3)); Jc[..., 0, 0] = zi; Jc[..., 0, 2] = -u * zi; Jc[..., 1, 1] = zi; Jc[..., 1, 2] = -v * zi
            J = np.einsum("cnij,cjk->cnik", Jc, R) * sg[..., None, None]
            H = np.einsum("cnij,cnik->njk", J, J); gr = np.einsum("cnij,cni->nj", J, res)
            H = H + (1e-12 * np.trace(H, axis1=1, axis2=2) + 1e-300)[:, None, None] * np.eye(3)
            upd = live & (g.sum(0) >= 2) & np.isfinite(H).all((1, 2)) & np.isfinite(gr).all(1)
            if not upd.any():
                break
            dX = np.zeros((N, 3))
            try:
                dX[upd] = -np.linalg.solve(H[upd], gr[upd][..., None])[..., 0]
            except np.linalg.LinAlgError:
                dX[upd] = -np.einsum("nij,nj->ni", np.linalg.pinv(H[upd]), gr[upd])
            X = np.where(live[:, None], X + dX, X)
            if not np.abs(dX[upd]).max() >= 1e-10:
                break
    return X


def _tri_core(cams: list[Camera], pts: np.ndarray, wts: np.ndarray, *, outlier_px: float | None, min_angle_deg: float, max_range_m: float,
              refine: bool) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """-> X [N,3], mean raw-px error over used views [N], used [C,N]; X/E NaN (used all False) where rejected."""
    C, N = wts.shape
    Tcw = [inv(c.T_world_cam) for c in cams]
    R = np.stack([T[:3, :3] for T in Tcw]); t = np.stack([T[:3, 3] for T in Tcw]); centres = np.stack([c.T_world_cam[:3, 3] for c in cams])
    f = np.array([np.sqrt(c.intr.K[0, 0] * c.intr.K[1, 1]) for c in cams])
    valid = np.isfinite(wts) & (wts > 0) & np.isfinite(pts).all(-1)
    xn = np.full((C, N, 2), np.nan)
    for c in range(C):
        if valid[c].any():
            xn[c, valid[c]] = undistort_points(cams[c].intr, pts[c, valid[c]])
    valid &= np.isfinite(xn).all(-1)
    iters = 10 if refine else 0

    def errors(X):
        Xc = np.einsum("cij,nj->cni", R, X) + t[:, None, :]
        e = np.stack([np.linalg.norm(project_cam(cams[c].intr, Xc[c]) - pts[c], axis=1) for c in range(C)])
        return e, Xc[..., 2]

    used = valid.copy(); X = _tri_solve(R, t, f, xn, wts, used, iters); E_c, depth = errors(X)
    if outlier_px is not None and C >= 3:
        # the joint fit spreads an outlier over all views (30 px in 1 of 3 views shows as ~12 px), so check consensus early
        need = (valid.sum(0) >= 3) & (valid & ~(E_c <= outlier_px / 3)).any(0)
        if need.any():  # MSAC over all view pairs (exhaustive; C is small), then refit on the best hypothesis' inliers
            best_n = np.zeros(N, int); best_cost = np.full(N, np.inf); best = np.zeros_like(valid)
            for a, b in combinations(range(C), 2):
                m = np.zeros_like(valid); m[a] = valid[a] & valid[b] & need; m[b] = m[a]
                if not m[a].any():
                    continue
                Ep, dp = errors(_tri_solve(R, t, f, xn, wts, m, iters))
                inl = valid & (Ep <= outlier_px) & (dp > _MIN_DEPTH_M)
                cost = np.where(valid, np.minimum(np.where(inl, Ep, outlier_px), outlier_px) ** 2, 0).sum(0)
                better = m[a] & (inl.sum(0) >= 2) & (cost < best_cost)
                best_n[better], best_cost[better] = inl.sum(0)[better], cost[better]; best[:, better] = inl[:, better]
            redo = need & (best_n >= 2)
            if redo.any():
                used[:, redo] = best[:, redo]
                Xr = _tri_solve(R, t, f, xn, wts, used & redo[None], iters); X[redo] = Xr[redo]
                E_c, depth = errors(X)
    n_used = used.sum(0)
    dist = np.linalg.norm(X[None] - centres[:, None], axis=-1)
    d = (X[None] - centres[:, None]) / np.where(dist > 0, dist, np.nan)[..., None]
    cosm = np.einsum("anj,bnj->nab", d, d)
    pair = used.T[:, :, None] & used.T[:, None, :] & ~np.eye(C, dtype=bool)[None]
    min_cos = np.where(pair, np.nan_to_num(cosm, nan=1.0), 1.0).min(axis=(1, 2))
    with np.errstate(invalid="ignore"):
        E = np.where(used, E_c, 0).sum(0) / np.maximum(n_used, 1)
        ok = ((n_used >= 2) & np.isfinite(X).all(1) & np.isfinite(E) & np.all(~used | (depth > _MIN_DEPTH_M), axis=0)
              & np.all(~used | (dist <= max_range_m), axis=0) & (np.degrees(np.arccos(np.clip(min_cos, -1, 1))) >= min_angle_deg))
    X[~ok] = np.nan; E = np.where(ok, E, np.nan); used[:, ~ok] = False
    return X, E, used


def triangulate(cams: list[Camera], pts_px: list[np.ndarray | None], weights: list[float] | None = None, *, outlier_px: float | None = 12.0,
                min_angle_deg: float = 2.0, max_range_m: float = 10.0, refine: bool = True) -> tuple[np.ndarray, float] | None:
    """One point from >= 2 views. pts_px: per camera a RAW pixel [2] or None (same length as cams). Returns (X_world [3],
    mean raw-px reprojection error over the views used) or None when fewer than 2 usable views remain, the point is
    behind a used camera, farther than max_range_m from one, or all ray pairs meet at < min_angle_deg. With >= 3 views a
    view inconsistent with the others by > outlier_px is dropped. weights (e.g. detector confidence) scale each view."""
    if len(pts_px) != len(cams) or (weights is not None and len(weights) != len(cams)):
        raise GeometryError(f"triangulate: {len(cams)} cameras but {len(pts_px)} observations" + ("" if weights is None else f" / {len(weights)} weights"))
    C = len(cams); pts = np.full((C, 1, 2), np.nan); w = np.zeros((C, 1))
    for c, p in enumerate(pts_px):
        if p is not None:
            a = np.asarray(p, float).ravel()
            if a.shape != (2,):
                raise GeometryError(f"triangulate: observation {c} has shape {np.shape(p)}, expected [2]")
            pts[c, 0] = a; w[c, 0] = 1.0 if weights is None else float(weights[c])
    X, E, _ = _tri_core(cams, pts, w, outlier_px=outlier_px, min_angle_deg=min_angle_deg, max_range_m=max_range_m, refine=refine)
    return None if not np.isfinite(E[0]) else (X[0], float(E[0]))


def triangulate_many(cams: list[Camera], pts: np.ndarray, conf: np.ndarray, min_conf: float = 0.4, max_err_px: float | None = 25.0, *,
                     outlier_px: float | None = None, min_angle_deg: float = 2.0, max_range_m: float = 10.0, refine: bool = True,
                     return_used: bool = False):
    """pts [C, N, 2] RAW pixels per camera per point, conf [C, N] (views with conf < min_conf or non-finite pixels are
    unused; the rest are weighted by conf). Returns X [N, 3] (world, metres) and err [N] (mean raw-px reprojection error
    over the used views), NaN where rejected: see triangulate, plus err > max_err_px. outlier_px (default max_err_px / 2,
    12 px without a gate) is the per-view consistency threshold for dropping views when >= 3 are available.
    return_used=True also returns used [C, N] (bool)."""
    pts = np.asarray(pts, float); conf = np.asarray(conf, float)
    if conf.ndim != 2 or pts.shape != (*conf.shape, 2) or conf.shape[0] != len(cams):
        raise GeometryError(f"triangulate_many: pts {pts.shape} / conf {conf.shape} must be [C, N, 2] / [C, N] with C = {len(cams)} cameras")
    if outlier_px is None:
        outlier_px = 12.0 if max_err_px is None else max_err_px / 2
    w = np.where(conf >= min_conf, conf, 0.0)
    X, E, used = _tri_core(cams, pts, w, outlier_px=outlier_px, min_angle_deg=min_angle_deg, max_range_m=max_range_m, refine=refine)
    if max_err_px is not None:
        bad = ~(E <= max_err_px); X[bad] = np.nan; E[bad] = np.nan; used[:, bad] = False
    return (X, E, used) if return_used else (X, E)


# ----------------------------------------------------------------------------- rig registration

def register_cameras_from_board(views: dict[str, tuple[np.ndarray, Intrinsics]], spec: BoardSpec, max_err_px: float = 3.0) -> dict[str, tuple[np.ndarray, float]]:
    """One RAW grayscale frame per camera that shows the board -> name -> (T_world_cam, mean reprojection px) for the
    cameras whose board pose passes (board_pose checks, error <= max_err_px). World = board frame. The frames must be
    simultaneous, or the board static between them, for the cameras to share one world."""
    out = {}
    for name, (gray, intr) in views.items():
        r = board_pose(gray, intr, spec, max_err_px=max_err_px)
        if r is not None:
            T_cam_board, err = r; out[name] = (inv(T_cam_board), err)  # T_world_cam with world == board
    return out
